[theme]

# Primary accent for interactive elements
primaryColor = '#151B54'

# Background color for the main content area
backgroundColor = '#123456'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#566D7E'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"